# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000
server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    url: jdbc:sqlite:/Project/2024CourseDesign/conflictProj/teach/java2/data.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin
  jpa:
    database-platform: org.fatmansoft.teach.sqlite.SQLDialect
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  jmx:
    enabled:false
# Mail server properties
  mail:
    host: smtp.sdu.edu.cn
    port: 25
    username: xqli@sdu.edu.cn
    password: 111
    properties:
      mail:
        smtp:
          auth: true
          connection timeout: 5000
          timeout: 5000
          write timeout: 5000
          starttls:
            enable: true
attach:
  folder: /teach/
logging:
  config: classpath:loggback.xml

